#!/bin/bash

##########################################
# Script for converting a form generated by gen_form.sh into a json at Boamps data model format
# Author : dfovet
# Version : 0.87
# Date : 20250717
##########################################

##########################################
# Usage
##########################################
usage()
{
echo "-----------------------------------------------------"
echo "Wrong Usage WARNING"
echo "-----------------------------------------------------"
echo "Purpose of the script : Convert a form generated by gen_form.sh into json at Boamps data model format"
echo ""
echo "Command structure: "
echo "./form2json.sh <Generation Type> <Reference CSV> <Form file to convert>"
echo "exemple: ./form2json.sh -a Ref_CodeCarbon.csv report1.txt > json_example.json"
echo "<Generation Type>"
echo " -a for ALL generates a json including mandatory and optional fields"
echo "<Reference CSV>"
echo "Descriptive file of the data model including or not the references to fill the form from a CSV"
echo "Example: Ref_CodeCarbon.csv To pre-fill the form from a CodeCarbon csv"
}

##########################################
# Log Management
##########################################
tolog()
{
LOGTIMETAG=`date +%Y\;%m\;%d\;%H\;%M\;%S\;%N`
echo "$LOGTIMETAG--$1" >> "$2"
echo "$LOGTIMETAG--$1"
}

tolognodate()
{
LOGTIMETAG=`date +%Y\;%m\;%d\;%H\;%M\;%S\;%N`
echo "$1" >> "$2"
echo "$LOGTIMETAG--$1"
}

##########################################
# Read from a file table separated by ;
##########################################
readtab()
{
    i=$2
    j=$3
    RES=""
    RES=$(sed -n ''$j','$j' p' "$1" | awk -v idx=$i -F';' '{print $idx}')
    echo "$RES"
}

##########################################
# Read a string in the form between = and # and trimming spaces before and after
##########################################
readlineval()
{
    j=$2
    RES=""
    #echo "<some text>=someuser@somedomain.com #<some text>" | sed 's/.*=$ .* $ #.*/\1/'
    RES=$(sed -n ''$j','$j' p' "$1" | sed 's/.*=$ .* $ #.*/\1/' | sed 's/^ *//;s/ *$//')
    echo "$RES"
}


##########################################
# Write identation for the json output file
##########################################
indentification()
{
    j=0
    tot=$1
    if [[ $tot != 0 ]]
    then
        for (( j=1; j<=$tot; j++ ))
        do
            echo -ne "\t"
        done
    fi
}

##########################################
# Init variables
##########################################
DATETAG=`date +%y%m%d-%H%M`
BASEDIR=$(pwd)
BASENAME0=$(basename "$0")
LOGDIR="$BASEDIR/Log"
NPARAMS=3
LOGFILE="$LOGDIR/$BASENAME0_$2_$DATETAG.log"
RESULTFILE="$LOGDIR/Result_$BASENAME0_$2_$DATETAG.log"
ficRef="$2"
ficForm="$3"
nbligneparam=$(wc -l < "$ficRef")
nbtab=0
nbtable=0
nbentry=1
idreadline=10
refline=2
indent=0
endline=""
tableList=();
reflineList=();
refList=();


##########################################
## Check the number of params
##########################################
if [[ $# -lt "$NPARAMS" || $# -gt "$NPARAMS" ]]
   then
       echo "ce script a besoin de $NPARAMS arguments en entree!"
       usage
exit 0
fi

##########################################
## Select execution mode
##########################################
case $1 in 
    "-a")
        mode="A"
        ;;
    "-m")
        mode="M"
        ;;
    *)
        echo "BAD Argument : $1"
        usage
        exit 0
esac

##########################################
## Retrieve generation params based on info from the form file to convert
##########################################
nbAlgo=$(readlineval "$ficForm" 2)
nbAlgoHyperparamVal=$(readlineval "$ficForm" 3)
nbDataset=$(readlineval "$ficForm" 4)
nbDatasetShape=$(readlineval "$ficForm" 5)
datasetInferenceProperties=$(readlineval "$ficForm" 6)
nbMeasures=$(readlineval "$ficForm" 7)
infraComponents=$(readlineval "$ficForm" 8)

##########################################
## Writing the start of the json file
##########################################

echo "{"
let "indent++"

##########################################
## Loop to read the reference file
##########################################
for ((refline=2; refline<=$nbligneparam; refline++))
do

    strName=$(readtab "$ficRef" 1 $refline)
    strType=$(readtab "$ficRef" 2 $refline)
    strMandatory=$(readtab "$ficRef" 3 $refline)
    strPath=$(readtab "$ficRef" 4 $refline)
    strKeyword=$(readtab "$ficRef" 5 $refline)
    strDescription=$(readtab "$ficRef" 6 $refline)
    strExample=$(readtab "$ficRef" 7 $refline)

    # Endline management
    if [[ $refline == $nbligneparam ]]
    then
        endline=""
    else 
        endline=","
    fi

    # Check the mandatory attribute to decide to export or not if the mode is set to mandatory only
    if [[ $mode == "M" && $strMandatory != "Y" ]]
    then
        let "idreadline++"
        continue
    fi

    case $strType in 
        "Object")
            echo "$(indentification $indent)\"$strName\": {"
            let "nbtab++"
            let "indent++"
            ;;

        "String")
            value=$(readlineval "$ficForm" $idreadline)
            if [[ $value != "" ]]
            then
              indentification $indent
              echo "\"$strName\":\"$value\"$endline"
            fi
            ;;

        "Table")     
            if [[ $nbtable -ne 0 ]]
            then
                if [[ ${tableList[$((nbtable-1))]} != "$strName" ]]
                then
                    tableList[$nbtable]="$strName"
                    reflineList[$nbtable]="$refline"
                    refList[$nbtable]=1
                    nbentry=1
                    
                    let "nbtable++"
                    echo "$(indentification $indent)\"$strName\": ["
                    let "indent++"
                    echo "$(indentification $indent){"

                fi
            else
                tableList[$nbtable]="$strName"
                reflineList[$nbtable]="$refline"
                refList[$nbtable]=1

                let "nbtable++"
                echo "$(indentification $indent)\"$strName\": ["
                let "indent++"
                echo "$(indentification $indent){"

            fi
            
            let "nbtab++" 

            ;;
       
        "TableEnd")
            
            array=("header End${IFS}task End${IFS}values End${IFS}shape End${IFS}inferenceProperties End${IFS}components End${IFS}algorithms End${IFS}dataset End${IFS}measures End${IFS}system End${IFS}software End${IFS}infrastructure End${IFS}environment End${IFS}\$hash End")
            isInArray="$strName"

            if [[ "${IFS}${array[*]}${IFS}" =~ "${IFS}${isInArray}${IFS}" ]]; then
                if [ $nbtab -gt 0 ]; then let "nbtab--" ; fi
            fi
            
            tableList=(${tableList[@]:0:$nbtable} ${tableList[@]:$(($nbtable + 1))})

            if [[ $strName == "algorithms End" ]]; then nbIter=$nbAlgo ; fi
            if [[ $strName == "values End" ]]; then nbIter=$nbAlgoHyperparamVal ; fi
            if [[ $strName == "shape End" ]]; then nbIter=$nbDatasetShape ; fi
            if [[ $strName == "inferenceProperties End" ]]; then nbIter=$datasetInferenceProperties ; fi
            if [[ $strName == "components End" ]]; then nbIter=$infraComponents ; fi
            if [[ $strName == "dataset End" ]]; then nbIter=$nbDataset ; fi
            if [[ $strName == "measures End" ]]; then nbIter=$nbMeasures ; fi

            if [[ ${refList[$((nbtable-1))]} < $nbIter ]]; then
                refList[$((nbtable-1))]=$((refList[$((nbtable-1))] + 1))
                nbentry=${refList[$((nbtable-1))]}
                refline=$((reflineList[$((nbtable-1))] - 1))

                #echo "$(indentification $indent)}$endline"
                echo "$(indentification $indent)},"
                echo "$(indentification $indent){"

            else
                let "nbtable--"
                refList=(${refList[@]:0:$nbtable} ${refList[@]:$(($nbtable + 1))})
                tableList=(${tableList[@]:0:$nbtable} ${tableList[@]:$(($nbtable + 1))})
                reflineList=(${reflineList[@]:0:$nbtable} ${reflineList[@]:$(($nbtable + 1))})
                nbentry=1

                echo "$(indentification $indent)}"
                let "indent--"  
                echo "$(indentification $indent)]$endline"

            fi  
            
            ;;
       
        "ObjectEnd")
            array=("header End${IFS}task End${IFS}measures End${IFS}system End${IFS}software End${IFS}infrastructure End${IFS}environment End${IFS}\$hash End")
            isInArray="$strName"

            if [[ "${IFS}${array[*]}${IFS}" =~ "${IFS}${isInArray}${IFS}" ]]; then 
                if [ $nbtab -gt 0 ]; then let "nbtab--" ; fi
            fi

            echo "$(indentification $indent)}$endline"
            let "indent--"

            ;;

    esac

    IFS="|"

    value=""
    let "idreadline++"

done

##########################################
# Finalisation of the json file
##########################################
echo "}"

